name: Deploy to Preview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        working-directory: scripts
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Link Vercel Project
        working-directory: ide
        run: vercel link --yes --project=themed-ide --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        working-directory: ide
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Create GitHub Deployment
        id: deployment
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              environment: 'preview',
              auto_merge: false,
              required_contexts: []
            });
            return deployment.data.id;

      - name: Update GitHub Deployment Status (In Progress)
        run: |
          python scripts/github_deployment.py \
            "${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.repository }}" \
            "${{ steps.deployment.outputs.result }}" \
            "in_progress"

      - name: Build Project Artifacts
        working-directory: ide
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ide
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Update GitHub Deployment Status (Success)
        if: success()
        run: |
          python scripts/github_deployment.py \
            "${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.repository }}" \
            "${{ steps.deployment.outputs.result }}" \
            "success" \
            "https://themed-ide.vercel.app"

      - name: Update GitHub Deployment Status (Failure)
        if: failure()
        run: |
          python scripts/github_deployment.py \
            "${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.repository }}" \
            "${{ steps.deployment.outputs.result }}" \
            "failure"
