name: Deploy to Preview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Preview'
      is_production: false
