name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-prd:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
      is_production: true
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
